# Generated by Django 5.2 on 2025-04-05 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0003_order_tracking_number_alter_order_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "В обработке"),
                    ("shipped", "Отправлено"),
                    ("delivered", "Доставлено"),
                ],
                default="processing",
                max_length=20,
            ),
        ),
    ]
