# Generated by Django 5.2 on 2025-04-06 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "marketplace",
            "0005_order_items_alter_order_user_alter_orderitem_order_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="items",
            new_name="products",
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "В обработке"),
                    ("shipped", "Отправлено"),
                    ("delivered", "Доставлено"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_items",
                to="marketplace.order",
            ),
        ),
    ]
