# Generated by Django 5.2 on 2025-04-22 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "marketplace",
            "0008_category_alter_review_product_alter_review_rating_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("image", models.ImageField(blank=True, null=True, upload_to="news/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
